platform :ios, '9.0'

target 'Sm2FrameworkDemo' do

  use_frameworks!

#   pod 'DBChainSm2'
   pod 'DBChainSm2', :path => '../'

#   pod 'HDWalletKit', :git => 'https://github.com/essentiaone/HDWallet.git'

#   pod 'HDWalletKit'
#   pod 'HDWalletKit'


#   , :git => 'https://github.com/vandyshev/HDWalletKit.git'
   
#   pod 'CryptoSwift'

  target 'Sm2FrameworkDemoTests' do
    inherit! :search_paths
    
#    pod 'DBChainSm2'
    pod 'DBChainSm2', :path => '../'

#    pod 'CryptoSwift'
  end

  target 'Sm2FrameworkDemoUITests' do
#    pod 'DBChainSm2'
    pod 'DBChainSm2', :path => '../'

#    pod 'CryptoSwift'
  end

end
